CactusPuppy/owarmory

package.json
pnpm-lock.yaml
src/lib/scss/_functions.scss
src/lib/scss/_mixins.scss
src/lib/scss/_variables.scss
src/routes/+page.svelte
svelte.config.js
vite.config.ts

This sets up SCSS with some basic variables, functions, and mixins. The function in particular is just as a placeholder to prove that it works.
All three files are imported globally as * so that we can use them without namespace and without having to reimport them.

chore: Set up SCSS

---

src/lib/components/content/BuildsList.svelte
src/routes/(main)/+page.svelte

Small and simple: just some placeholder text to make it clear there should be builds there normally, but for one reason or another they aren't there!

feat: add placeholder text for empty build lists

---

src/lib/components/layout/Search.svelte

This is to fix a depcrecation warning

chore: Use percentage in lightness for search form background

---

src/lib/components/content/Build.svelte

Merge conflicts gone wild, I imagine

chore: Reorder imports

---

e2e/api/talents/items.test.ts
e2e/api/talents/powers.test.ts
package.json
playwright.config.ts
src/database/prismaClient.server.ts
src/lib/types/hero.ts

This PR adds the basics for testing API endpoints and the overall UI. Not a lot added right now because we're still getting the site up to v1 :)

test: e2e testing

---

src/lib/components/content/Item.svelte
src/lib/components/content/Power.svelte

chore: Add width and height to item and power

---

src/lib/components/content/SharedDetail.svelte
src/lib/components/content/StatMods.svelte
src/lib/utils/stat.ts

refactor: Extract stat mods to separate component

---

src/routes/(main)/privacy/+page.svelte

We don't do much that requires telling the user about, but we still need a privacy policy.

chore: Add simple privacy policy

---

src/lib/components/form/BuildForm.svelte
src/lib/types/build.ts
src/routes/api/build/form/+server.ts

This PR adds the backend endpoint for editing builds

fix: enable builds to be edited

---

src/lib/components/form/ShareInput.svelte
src/lib/scss/_variables.scss
src/lib/utils/routes.ts
src/routes/(main)/build/[id]-[slug]/+page.svelte

A simple input-like share box with a button to easily copy the URL. The input itself also automatically selects all text when you focus it.

feat: Share builds

---

src/lib/components/form/DeleteBuild.svelte
src/lib/scss/elements/_buttons.scss
src/routes/(main)/build/[id]-[slug]/edit/+page.svelte
src/routes/api/build/form/+server.ts

This adds deleting form builds. Each association is deleted individually when the build is delete.
The button requires a confirmation after pressing the delete button.

feat: Add deleting of builds

---

src/lib/components/content/Build.svelte

fix: Prevent line break in build author

---

src/routes/(main)/+page.svelte

We were lacking a description, now we got one! I had trouble coming up with a good sentence, hopefully this will do.

chore: Add meta description to homepage

---

src/routes/(main)/randomizer/+page.svelte
src/routes/(main)/randomizer/+page.ts

This PR adds a really quick and janky item/power randomizer on rush order from Salty Phish and R3trohowling.

feat: add a really jank talent randomizer

---

src/routes/(main)/randomizer/+page.svelte

Add helper text to explain which category the item is in, an option to set a budget, and a button to roll a new hero.

feat: add item category to randomized item and add some other utilities

---

src/routes/(main)/randomizer/+page.svelte

This PR adds an option to restrict item selection to a specific category.

feat: add item category restriction

---

src/lib/components/layout/Search.test.ts

Just some basic tests to verify submitting the search form works as expected.

test: Add unit tests for Search component

---

src/lib/components/content/Build.svelte
src/lib/components/layout/Navigation.svelte
src/lib/components/layout/Search.test.ts
src/lib/types/build.ts

Changes:
- Adds alt text to mobile logo (#148)
- Wrap build name when necessary (#146)
- Avoid including statmods in stats (#147)
- Add unit tests for Search component (#149)

2025-05-18 Production Push

---

src/lib/components/content/Hero.svelte
src/lib/utils/routes.ts
src/routes/(main)/hero/[heroName]/+page.svelte
src/routes/sitemap/+server.ts

Changes:
- [chore(seo): Adjust title for hero pages](https://github.com/CactusPuppy/owarmory/commit/c55a8cfd88467b106684b79a5f6b0a01c33db03c)
- [feat: Add sitemap with generated paths](https://github.com/CactusPuppy/owarmory/commit/8d31a53b6d60bb3171970363a9cbc50bfa1d3a6f)

2025-05-19 Production Push 

---

src/routes/sitemap/+server.ts

fix: Use iso date for build lastmod in sitemap

---

src/routes/sitemap/+server.ts

Changes: 
- [fix: Use iso date for build lastmod in sitemap](https://github.com/CactusPuppy/owarmory/commit/a577733dc6bcc8121926d0352cbd7337f8cc9741)

2025-05-19 #2 Production Push 

---

src/lib/components/form/BuildForm.svelte

We haven't added any tags yet, so this PR hides them while they are empty.

chore: Hide tags while we haven't set them up

---

src/lib/components/content/Item.svelte
src/lib/components/content/SharedDetail.svelte
src/lib/components/content/TalentRichInsert.svelte

This PR adds the item category to the details of items, so as to facilitate faster location of the item.

feat: add item category to SharedDetail

---

src/lib/components/content/Item.svelte
src/lib/components/content/SharedDetail.svelte
src/lib/components/content/TalentRichInsert.svelte

This PR adds the item category to the details of items, so as to facilitate faster location of the item.

feat: add item category to SharedDetail (#165)

---

prisma/migrations/20250527052837_add_user_roles/migration.sql
prisma/schema.prisma
src/lib/auth.ts
src/lib/components/content/TalentsNavigation.svelte
src/lib/types/build.ts
src/routes/admin/+layout.server.ts
src/routes/admin/+layout.svelte
src/routes/admin/+page.svelte
src/routes/admin/talents/+layout.svelte
src/routes/admin/talents/+server.ts
src/routes/admin/talents/items/+page.svelte
src/routes/admin/talents/items/+page.ts
src/routes/admin/talents/items/[id]/+layout.server.ts
src/routes/admin/talents/items/[id]/+layout@admin.svelte
src/routes/admin/talents/items/[id]/edit/+page.server.ts
src/routes/admin/talents/items/[id]/edit/+page.svelte
src/routes/admin/talents/powers/+page.svelte
src/routes/admin/talents/powers/+page.ts
src/routes/admin/talents/powers/[id]/+layout.server.ts
src/routes/admin/talents/powers/[id]/+layout@admin.svelte
src/routes/admin/talents/powers/[id]/edit/+page.server.ts
src/routes/admin/talents/powers/[id]/edit/+page.svelte

This PR adds an admin interface for updating items and powers without needing a full redeploy.

feat: admin tools
