CactusPuppy/owarmory

src/lib/components/common/Popover.svelte
src/lib/components/content/Item.svelte
src/lib/components/content/Power.svelte
src/lib/components/content/SharedDetail.svelte
src/lib/scss/_variables.scss
src/routes/(main)/+page.svelte

This merges into #5 and should be rebased after merging that PR first.
This adds the components for hoverable items and powers. Both are separate components that are fairly similar is shape, but just different enough to warrant different components. They share two componts;
- Popover, which is a hover tooltip. This does not yet contain any logic for better positioning when the tooltip falls offscreen (like on mobile).
- SharedDetail, which is the description that appears in the Popover. This is made to look as close to the game as possible, but I didn't add quite everything yet, icons are missing.
This uses placeholder images, which do look like crap, but please look past that!

feat: Add item and power components

---

src/lib/components/common/Popover.svelte
src/lib/components/content/Build.svelte
src/lib/components/content/BuildsList.svelte
src/lib/scss/_variables.scss
src/lib/scss/global.scss
src/routes/(main)/+page.svelte

This adds the builds list with individual build items. I'm not yet entirely satisfied with the view on mobile, and there's some bad breakpoints, but I will improve that in a separate PR later.
The builds are clickable but are not themselves <a> tags, because we can't have <a> tags inside of other <a> tags.
The content is all of course placeholder stuff.

feat: Builds list

---

src/lib/components/content/ItemStastisticsBar.svelte
src/lib/components/content/ItemStatistics.svelte

This is a somewhat in-between solution that adds armor and health values to statistics bars, without going to full segmented route like in-game. I do still want to add that at some point since they are easier to read, but for now this is a simple solution using a linear-gradient that still allows us to display the armor and health values in in some.

feat: Add styling for armor and health to statistic bars

---

src/lib/components/content/RoundInfo.svelte
src/lib/types/build.d.ts
src/routes/(main)/build/[slug]/+page.svelte

Merges into #9, which should be merged first, and this should be rebased
This adds a static version of the round info to the detail page. The contains the individual rounds as well as the description. With a variant for mobile as well.
Once again I made some assuptions for types and suchs. Feel free to totally ignore these, these were just temporary to make development life a little easier.

feat: Add round info to build detail page

---

src/lib/components/content/CompoundedBuild.svelte
src/lib/components/content/DashedHeader.svelte
src/lib/components/content/Item.svelte
src/lib/components/content/Power.svelte
src/lib/data/testData.ts
src/lib/scss/_variables.scss
src/lib/utils/build.ts
src/routes/(main)/build/[slug]/+page.svelte

This adds the "final" build to the sidebar of the detail page. This final build is derived from the items and powers per section, adding them up.
- There's not yet any logic for sold items.
- Types in the new `utils/build` function are not quite right because we don't have the actual types yet.
To make sure the grid is always filled out, we add skeletons to indicate that something _will_ be there in later rounds. In final rounds we'd expect all slots to be filled.
This build can already be narrowed down by round, but there's no controls for it yet. For example, this is round 1 of the same build above. It uses the exact same dataset, the shown build is derived from the build itself and the round number.

feat: Add compounded build to sidebar on build detail page

---

src/lib/components/content/Build.svelte
src/lib/components/content/BuildsList.svelte
src/lib/components/content/CompoundedBuild.svelte
src/lib/components/content/RoundSelector.svelte
src/lib/constants/round.ts
src/lib/types/round.ts
src/routes/(main)/+page.svelte
src/routes/(main)/build/[slug]/+page.svelte

Merges into #14, which should be merged first
This PR adds a round selector to both the detail and homepage. The rounds are passed and set via a state rune in setContext. This is done rather than a global store to make it easier to manage per page. With it being a state on the page itself, the value is shared between anything on the page that might use it. On the homepage this is relevant for the different build lists.

feat: Add round selector 

---

src/lib/actions/closeable.ts
src/lib/components/common/Popover.svelte

On desktop the interaction is a simple hover, and closing the popover doesn't require extra actions. With touch screens, however, that is a bit different. The popovers are opened on tap, and closed by tapping the same element. This PR adds another way, and that is by tapping anywhere but the element itself. Or pressing escape, for good measure.

feat: Allow popover to be closed via outside click or escape

---

prisma/migrations/20250429035827_add_user/migration.sql
prisma/schema.prisma
prisma/seed.ts
src/lib/components/layout/Navigation.svelte
src/lib/components/user/UserMenu.svelte
src/lib/constants/auth.ts
src/lib/types/user.d.ts
src/lib/utils/api.ts
src/routes/(main)/+layout.svelte
src/routes/(main)/+layout.ts
src/routes/+layout.server.ts
src/routes/+layout.svelte
src/routes/api/login/+server.ts
src/routes/api/logout/+server.ts

We'll want to keep track of the logged in user somehow, and it needs to work SSR and CSR. We can't store it in a store or a state rune, as these are shared on the server, meaning data could leak from one user to the next. Instead we store an auth token in a cookie. This cookie is used to fetch the user from database. From here the user object is passed via the layout and down to any other load function that might use it. This same object is set via the context api via `setContext`. To make sure this is updated whenever the state on the server changes (eg, the user logs out or in), the main layout is wrapped in a `#key`. Whenever the actual `data.currentUser` object is changed, the whole layout is re-rendered, forcing `setContext` to be run again. This can then be used by any component …

feat: Set up simple state for currentUser

---

src/lib/components/content/Build.svelte

Items would not fit correctly on mobile screens, no longer!
Before | After
--- | ---

style: Wrap items in build list items

---

prisma/schema.prisma
prisma/seed.ts
src/lib/types/build.ts
src/lib/utils/faker/build.ts

This PR ensures that models save their order, because Prisma does not do it for us.

fix: add order to models

---

prisma/migrations/20250430232124_add_ordering/migration.sql

Forgot to include the migration generated by #31. Oopsie.

fix: include migration for adding ordering

---

package.json
pnpm-lock.yaml
src/routes/(main)/build/[slug]/+page.svelte

This adds markdown to the large description section. I chose [snarkdown](https://github.com/developit/snarkdown) because it's nice and light weight and probably does all we need. What is less lightweight is [DOMPurify](https://github.com/cure53/DOMPurify), but after minifying+gzip that too is bad at all at only 9kb.

feat: Add markdown to additionalNotes section

---

src/routes/(main)/build/[slug]/edit/+page.server.ts

No leading slashes! Quite confusing, maybe we should enforce it the other way around instead?

fix: Use correct paths for talent api paths

---

src/routes/(main)/+page.svelte

We're not tracking popularity at the moment, so the section is useless.

chore: Remove popular builds section

---

src/lib/components/content/Item.svelte

Small and simple: since rarity classes are capitalized but we expect them to be lowercase, we need to convert the rarity for the CSS

fix: ensure rarity classes are properly applied

---

src/lib/scss/elements/_buttons.scss

Wrapping is hardly ever wanted in buttons, in this case it messed with the sign in button in the navigation
Before | After
--- | ---

style: Disable wrapping on buttons

---

src/lib/components/auth/SignInButton.svelte
src/lib/components/content/CreateBuildButton.svelte
src/lib/components/layout/Navigation.svelte
src/lib/scss/elements/_buttons.scss

Merges into #45 
This adds a button to the navigation to create a new build. When logged out this button functions as a sign in button, when logged in it's a link to the build form.
Logged out
Logged in

feat: Add Create build button to navigation

---

src/lib/components/common/Card.svelte
src/lib/components/content/SharedDetail.svelte
src/lib/components/form/ItemsGrid.svelte
src/lib/components/form/PowersGrid.svelte
src/lib/scss/global.scss

- Powers didn't use the full variant in powers grid
- Cards didn't fill the full height in the powers grid
- Added missing hover for items and powers in grid
- Adjust spacing and font sizes
Before | Before with full cards | After
--- | --- | ---

style: Fix several styling inconsistencies in power and item grids

---

src/lib/components/content/Item.svelte

When first creating the items I assumed the icons would be PNGs, they are not. Turns out that's good, because hero specific icons don't have consistent background colors.
Before | After
--- | ---

fix: Fill out entire icon circle in items

---

src/lib/components/form/ItemsGrid.svelte

Similar to #47, but in the form grids instead
Before | After
--- | ---

fix: Use lowercase rarity in grid

---

src/lib/components/form/ItemsGrid.svelte

To match the sorting in-game, the items are sorted first by whether or not they are hero specific, and after by cost.
Before | After
--- | ---

fix: Sort items in itemsGrid by cost and hero specific-ness

---

src/lib/components/form/BuildForm.svelte

To make a little more space and make the build form feel a bit cleaner, this PR removes one inset in tabs. Basically removing one depth of paddings. Easier explained in screenshots!
Before | After
--- | ---

style: Simplify tabs in build form

---

src/lib/components/content/SharedDetail.svelte

Makes the text feel that much more readable.
Before | After
--- | ---

style: Mark bracketed strings in talent descriptions

---

src/lib/components/content/SharedDetail.svelte
src/lib/components/form/ItemsGrid.svelte
src/lib/components/icon/CurrencyIcon.svelte
src/lib/images/icons/currency.svg
src/routes/(main)/build/[id]-[slug]/+page.svelte

I traced the icon manually and it's not perfect :|. I couldn't find it in the datatool vector images, but hey, it's close.

feat: Use currency icon instead of dollar sign for item cost

---

src/lib/components/content/RoundInfo.svelte

Items were supposed to be using their full variant, and the parent element was removed

fix: Incorrect merge

---

src/lib/scss/_variables.scss

This color is used primarily for text, for this purpose it was just slightly out of proper contrast ratios. This change makes that color just a little lighter, pushing it a 4.5 contrast ratio, it was 3.5 before.
Before | After
--- | ---

style: Use slightly lighter color for secondary variable

---

src/lib/components/form/BuildForm.svelte

This PR fixes two bugs with the build form:
1. Round notes were not correctly updated in both the build data.
2. It was possible to end up in a bad state by setting up a scenario such as buy > sell > buy, then removing the middle sale.
[Screencast_20250503_001038.webm](https://github.com/user-attachments/assets/5a210cec-9d97-4872-b1b7-cc848e56b92e)

fix: build form bugs

---

src/lib/components/layout/NavigatingIndicator.svelte
src/routes/(main)/+layout.svelte

When waiting for a new page to load, it can seem like nothing is happening. Of course usually it's fast enough to where it's not a problem, but sometimes it's not. This PR adds a loading indicator similar to that of Turbolinks to make it obvious that _something_ is happening.

feat: Turbolinks-like navigating indicator

---

src/lib/components/content/Power.svelte

The border for items was adjusted, for powers they were still a little different. Additionally, the border radius wasn't correct for large icons
Before | After
--- | ---

style: Use more consistent border for power icons

---

src/lib/components/content/BuildItemOrder.svelte
src/lib/components/content/BuildPowersOrder.svelte

Just to make them stand out a little more, and have them fit in a little better.
Before | After
--- | ---

style: Add backdrops to purchase orders

---

src/routes/(main)/+page.svelte

Same strategy as on other pages

fix: Only show load more button on homepage when relevant

---

src/routes/(main)/items/+page.svelte
src/routes/(main)/items/+page.ts
src/routes/(main)/powers/+page.svelte
src/routes/(main)/powers/+page.ts

To help us debug and find incorrect powers/items, this PR adds a powers and items page that simply lists all powers or items, grouped by hero.
This isn't really meant to be a public page, so it's super basic and not all that well made. Maybe one day these could be public facing, with a little search bar too, that'd be neat.
Powers | Items
--- | ---

feat: Add full items and powers pages

---

src/lib/components/form/BuildForm.svelte
src/lib/components/form/ItemsGrid.svelte
src/lib/components/form/PowersGrid.svelte

To make finding the right item just that little bit easier, you can now search! Search works by searching on the entire item or power object, stringified. Super simple and dumb, but it also works just fine.
Please ignore the gif crapping itself

feat: Add search to items and powers grid

---

src/lib/components/form/ItemsGrid.svelte

All general items are sorted by cost and then by name. For hero specific items that's less so the case, _most_ items seem to be sorted by name, but not all. So even this sorting isn't quite right, but it is one step closer. The only proper sorting seems to be to do it manually, which I'm not sure is worth the extra effort. Largely because hero specific items aren't exactly plentyful anyway.

fix: Additionally sort items by name

---

src/routes/api/build/form/+server.ts

The description was not included when posting a title, always leaving it empty. I could have included just the description, but is there any reason not to just spread validatedBuild?

fix: Include description in post

---

src/routes/(main)/[buildId]/+server.ts

This PR adds a small redirect from that page to the full build page. The idea is to allow the user to copy a shortlink which is easily shareable. While this PR doesn't add that to the build page yet, it does set up the backend for that feature!

chore: allow links in form of `/[build-id]`

---

src/routes/(main)/build/[id]-[slug]/+page.svelte

Tiny thing, but this was supposed to be there but got lost between merges. Additionally, I've adjusted the divider to break sections on mobile.
Before | After
--- | ---
On mobile it shows each segment on a separate line.

style: Add divider between tags and author

---

src/lib/components/content/BuildItemOrder.svelte

This PR adds a small little placeholder text to the item purchase order.

feat: add placeholder for item purchase order

---

src/lib/components/form/BuildForm.svelte

It already was 1500 in the backend, the frontend limited it to 500.
Closes #120

chore: Increase note length to 1500

---

src/routes/(main)/build/[id]/[slug]/+page.svelte

Closes #119 
Before | After
--- | ---

fix: Don't show tags divider when no tags are given

---

src/lib/components/content/Healthbar.svelte
src/lib/components/content/Item.svelte
src/lib/components/content/ItemStastisticsBar.svelte
src/lib/components/content/Power.svelte
src/lib/components/content/TalentRichInsert.svelte

We're loading quite a few images, many of which might be offscreen. Not necessarily, so we might cause some images to load slightly later than might be ideal, but non of these images are crucial to the layout to the point where the extra millisecond makes the difference.

chore: Use lazy loading for many images

---

src/lib/utils/markdown.ts

Snarkdown doesn't support paragraphs. Any amount of newlines are always replaced with single breaks. Paragraphs are cool and we want them, but we actually can't easily do that. We can't use paragraph directly because of how we parse talent previews. Instead, here we use double linebreaks, which visually gives the same appearance.
Before | After
--- | ---

fix: Insert double line breaks where relevant in markdown content

---

src/routes/(main)/hero/[heroName]/+page.svelte

Helps with navigating between heroes. I also have to change `builds` to a derived rune so that the list updates as expected when `data` changes.
Before | After
--- | ---

feat: Add hero select to hero pages

---

src/lib/utils/markdown.ts
svelte.config.js

Basic testing with examples provided by DOMPurify results in no leakage beyond style tags.
It's better to provide a good experience now than to hold off for a perfect defense-in-depth.

fix: avoid using DOMPurify (for now) and rely on browser CSP to block bad stuff

---

src/lib/components/content/RoundInfo.svelte

I'm a bit hesitant to allow full markdown in round info notes. Having full on titles is a bit much there, having bold and italic would be nice, but anything more than that might be a bit much. Talent previews seems like a good idea, though!

feat: Allow talent previews in round info notes

---

src/lib/components/content/RoundInfo.svelte

I'm a bit hesitant to allow full markdown in round info notes. Having full on titles is a bit much there, having bold and italic would be nice, but anything more than that might be a bit much. Talent previews seems like a good idea, though!
---------

feat: Allow talent previews in round info notes (#131)

---

src/lib/components/layout/Navigation.svelte

The desktop logo had a proper alt tag, but the mobile one was left empty. No real reason that would be intended.

chore: Add alt text to mobile logo

---

src/lib/components/content/Build.svelte

When a build has a very long name, it pushes the items into a very tight space. This fixes that by instead allowing build titles to wrap, leaving an equal space for the title and items when necessary.
Before | After
--- | ---

fix: Wrap build name when necessary

---

src/lib/types/build.ts

For a reason that I'm not 100% sure on, the `stat` field in `statMods` included `statMods` itself, which then seemed to include all `statMods` relations ever created for that stat? This resulted in builds having giant arrays of irrelevant statmods on each stat that only grows as more builds are created. JSON returns for builds could easily be be up to 1MB already, and overview pages could be 5MB+ already.
Anyway, this fixes that by no longer including `statMods` within `stat`, only returning the relevant fields instead.
Before:
After:

fix: Don't include full statmods in stats

---

src/routes/(main)/hero/[heroName]/+page.svelte

People might be likely to google for "Reinhardt stadium builds" or something along those lines. by including all those words in the h1, we might rank better for those searches.

chore(seo): Adjust title for hero pages

---

src/lib/components/content/Hero.svelte

With 1 hero added the hero grid layout turns quite ugly. Reducing it ever so slightly takes care of that on desktop layouts. Once more heroes are added we can up this back to 50 again.

style: Slightly reduce hero size

---

src/lib/components/form/BuildForm.svelte

On mobile tabs were hardly useable because you could not see all tabs. This takes care of that by allowing you to scroll.
Before | After
--- | ---

style: Allow scrolling in tabs

---

package.json
pnpm-lock.yaml
src/lib/components/content/Build.svelte
src/routes/(main)/build/[id]/[slug]/+page.svelte

This PR adds text which informs the user about when a given build was last updated in the build list, along with changing "Last updated" text to use relative units instead of absolute dates. Absolute dates are still visible on hover.
**Motivation**:
As Stadium is frequently balanced, builds which may have been top-tier in previous patches may become less powerful (intentionally so!) as the team balances the game. Adding information about when a build was last updated enables players to make more informed decisions about which builds to examine further.

feat: show time since build update in list

---

src/lib/components/form/BuildForm.svelte
src/lib/utils/string.spec.ts
src/lib/utils/string.ts
src/routes/(main)/(talents)/+layout.svelte
src/routes/admin/talents/+layout.svelte

This PR adds the ability to search for items and powers with lookalike ASCII characters. For example, searching for "Rüstung von Wilhelm" previously did not appear with the search term "Rustung", but now it does.
[Screencast_20250622_235241.webm](https://github.com/user-attachments/assets/dd397ad9-623d-4c91-ae81-87a437ae01d6)

feat: enable ascii characters to search for unicode lookalikes
